export const alsoServeSpecialties = [
  "Oral and Maxillofacial Surgery",
  "General Practice",
  "Chiropractor",
  "Dermatology",
  "Podiatry",
  "Endocrinology",
  "Osteopathic",
  "Occupational Therapy",
  "Vascular Surgery",
  "Urology",
  "Speech Therapy",
  "Physical Therapy",
  "Plastic Surgery",
  "Physiotherapy",
  "NEMT",
  "ENT",
  "Otolaryngology",
  "Laboratory",
  "Pain Management",
  "Gastroenterology",
  "Oncology",
  "Neurology",
  "Neonatology",
  "Mental Health",
  "Infectious Disease",
  "Hepatology",
  "Hematology",
  "Geriatrics",
  "Pharmacy",
  "Acupuncture",
  "Home Health Agencies",
];
